### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by Alberto796** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Alberto796#2]
![Mapa mental](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Alberto796/assets/143294848/bb327b82-b0a9-4571-a703-4176c65712cf)
![Mapa mental](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Alberto796/assets/143294848/3655f117-9b0e-4795-9f0e-21a0fe3fef9e)

**Comment by carla1131** [comment]
Manejo conceptual y dominio del tema (orden, jerarquía, aspecto visual y conceptos): 20%
Relación entre los conceptos incluidos en el mapa:16%
Calidad de la presentación:22%
Jerarquía:19%
Total:15.4%
calificado por Carla Leon

**Comment by josealfredo79** [comment]
Revisado...
